services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloakpassword
      - POSTGRES_DB=keycloak
    networks:
      - keycloak-network
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
      - MONGO_INITDB_DATABASE=keycloak_db
    networks:
      - keycloak-network
    restart: always
    volumes:
      - mongodb_data:/data/db

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 7080
      KC_HOSTNAME_STRICT_BACKCHANNEL: 'true'
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: 'true'
      KC_LOG_LEVEL: info
      DB_VENDOR: postgres
      DB_ADDR: postgres:5432
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloakpassword
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:7080/health/ready']
      interval: 15s
      timeout: 2s
      retries: 15
    command: ['start-dev', '--http-port', '7080', '--https-port', '7443']
    ports:
      - '7080:7080'
      - '7443:7443'
    depends_on:
      - postgres
    networks:
      - keycloak-network
    restart: always
    volumes:
      - keycloak_data:/opt/keycloak/data

networks:
  keycloak-network:
    driver: bridge

volumes:
  keycloak_data:
  postgres_data:
  mongodb_data:
